" Don't retain compatibility with vi
set nocompatible
" Disable filetype plugin
filetype off

source ~/.vim/vim-plug/plug.vim

call plug#begin('~/.vim/plugged')
" Plugins
Plug 'tpope/vim-fugitive'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'bling/vim-bufferline'
Plug 'wycats/nerdtree', { 'on':  'NERDTreeToggle' }
Plug 'ervandew/supertab'

"Plug 'majutsushi/tagbar'
Plug 'airblade/vim-gitgutter'

"Plug 'scrooloose/syntastic'
Plug 'w0rp/ale'
Plug 'christoomey/vim-tmux-navigator'
Plug 'junegunn/fzf'
Plug 'junegunn/fzf.vim'
Plug 'Valloric/YouCompleteMe'

" Color schemes
Plug 'junegunn/seoul256.vim'
Plug 'w0ng/vim-hybrid'
Plug 'zeis/vim-kolor'
Plug 'nanotech/jellybeans.vim'
Plug 'morhetz/gruvbox'
Plug 'chriskempson/base16-vim'
Plug 'altercation/vim-colors-solarized'

" Syntax highlighting
Plug 'kelwin/vim-smali'
Plug 'tmux-plugins/vim-tmux'
Plug 'Firef0x/PKGBUILD.vim'

" Other
Plug 'ap/vim-css-color'
call plug#end()

filetype plugin indent on

""""""""""""""""
" 24-bit color "
""""""""""""""""

if (has("nvim") && v:version <= 704)
    " Not needed in newer versions of neovim
    let $NVIM_TUI_ENABLE_TRUE_COLOR=1
endif
if (has("termguicolors"))
    " https://github.com/lifepillar/vim-solarized8/issues/1
    set t_8f=[38;2;%lu;%lu;%lum
    set t_8b=[48;2;%lu;%lu;%lum
    set termguicolors
endif

""""""""""""""""""
" Basic settings "
""""""""""""""""""

" Fix backspace
set backspace=indent,eol,start

" Enable syntax highlighting
syntax on

" Enable line numbering
set number

set expandtab
set tabstop=4
set shiftwidth=4

" Highlight all pattern matches
set hlsearch

" http://www.johnhawthorn.com/2012/09/vi-escape-delays/
set timeoutlen=1000 ttimeoutlen=0

"""""""""""""""
" vim-airline "
"""""""""""""""

" Always display the status line in all windows
set laststatus=2
" Always display the tab line, even if there is only one tab
" set showtabline=2
set showtabline=1
" Hide the default mode text (e.g. -- INSERT -- below the status line)
set noshowmode

let g:solarized_termcolors=256
" let g:airline_powerline_fonts = 1
"let g:airline#extensions#tabline#enabled = 1

" https://github.com/airblade/vim-gitgutter/issues/287
" autocmd VimEnter * :AirlineRefresh

""""""""""""
" nerdtree "
""""""""""""

" Open nerdtree with Ctrl+n
map <C-n> :NERDTreeToggle<CR>

"""""""""""""""""
" Color schemes "
"""""""""""""""""

" 256 colors
set t_Co=256

" Color scheme
"set background=light
set background=dark

colorscheme solarized
let base16colorspace=256
" colorscheme base16-tomorrow-night

""""""""
" Vala "
""""""""

autocmd BufRead *.vala,*.vapi set efm=%f:%l.%c-%[%^:]%#:\ %t%[%^:]%#:\ %m
au BufRead,BufNewFile *.vala,*.vapi setfiletype vala
