" Don't retain compatibility with vi
set nocompatible
" Disable filetype plugin
filetype off
" Add vundle to the runtime path
set rtp+=~/.vim/bundle/Vundle.vim
" Initialize vundle
call vundle#begin()
" Let Vundle manage itself
Plugin 'gmarik/Vundle.vim'
" Plugins
Plugin 'tpope/vim-fugitive'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'bling/vim-bufferline'
Plugin 'wycats/nerdtree'
Plugin 'ervandew/supertab'
Plugin 'majutsushi/tagbar'
Plugin 'airblade/vim-gitgutter'
Plugin 'scrooloose/syntastic'
Plugin 'christoomey/vim-tmux-navigator'
" Color schemes
Plugin 'junegunn/seoul256.vim'
Plugin 'w0ng/vim-hybrid'
Plugin 'zeis/vim-kolor'
Plugin 'nanotech/jellybeans.vim'
Plugin 'morhetz/gruvbox'
Plugin 'chriskempson/base16-vim'
" Syntax highlighting
Plugin 'kelwin/vim-smali'
Plugin 'tmux-plugins/vim-tmux'
Plugin 'Firef0x/PKGBUILD.vim'
" Required, plugins available after
call vundle#end()
filetype plugin indent on

""""""""""""""""""
" Basic settings "
""""""""""""""""""

" Enable syntax highlighting
syntax on

" Enable line numbering
set number

set expandtab
set tabstop=4
set shiftwidth=4

" Highlight all pattern matches
set hlsearch

" http://www.johnhawthorn.com/2012/09/vi-escape-delays/
set timeoutlen=1000 ttimeoutlen=0

"""""""""""""""
" vim-airline "
"""""""""""""""

" Always display the status line in all windows
set laststatus=2
" Always display the tab line, even if there is only one tab
" set showtabline=2
set showtabline=1
" Hide the default mode text (e.g. -- INSERT -- below the status line)
set noshowmode

let g:airline_powerline_fonts = 1
"let g:airline#extensions#tabline#enabled = 1

" https://github.com/airblade/vim-gitgutter/issues/287
autocmd VimEnter * :AirlineRefresh

""""""""""""
" nerdtree "
""""""""""""

" Open nerdtree with Ctrl+n
map <C-n> :NERDTreeToggle<CR>

"""""""""""""""""
" Color schemes "
"""""""""""""""""

" 256 colors
set t_Co=256

" Color scheme
"let base16colorspace=256
"colorscheme base16-default

""""""""
" Vala "
""""""""

autocmd BufRead *.vala,*.vapi set efm=%f:%l.%c-%[%^:]%#:\ %t%[%^:]%#:\ %m
au BufRead,BufNewFile *.vala,*.vapi setfiletype vala
